### ISSUE TITLE
Render items

### ISSUE THREAD

**Issue by AshleyLerma** [The-CallBack-Cats/BagIt#78]
Make items render to the page using props.

**Comment by antoniojgage** [comment]
Give me more ![image](https://user-images.githubusercontent.com/7440005/89742292-39386680-da5e-11ea-9894-5a506ac43523.gif)

**Comment by kholder777** [comment]
In client/src/components/department.js.
We are trying to render the items_name inside the itemBar shown in department.js.
The API has all required information, but it still wont render on the user's page.

**Comment by antoniojgage** [comment]
@kholder777 no errors in inspect?

**Comment by antoniojgage** [comment]
https://github.com/The-CallBack-Cats/BagIt/blob/77-showItemsOnPage/client/src/components/department.js

You're pushing an array into an array. Is that what you mean to do? Before pushing it, I'd suggest consoling it or setting it to state. Also, you're not using it anywhere in your return statement of the JSX
