### ISSUE TITLE
Create a Add User API & Tweak Items 

### ISSUE THREAD

**Issue by juanlajara** [The-CallBack-Cats/BagIt#82]
As a API Developer
I need to add an API that creates a new user
And Add all Category Names to Items API

**Comment by juanlajara** [comment]
![Screen Shot 2020-08-09 at 10 18 07 PM](https://user-images.githubusercontent.com/54958540/89749651-40776880-da8e-11ea-8f67-01ab43a63173.png)

**Comment by juanlajara** [comment]
`router.post("/create", function (req, res) {
	// replace old function with sequelize function
	db.User.create(
		{
			// user_name: req.body.user_name,
			user_name: "TestIt",
		},
		{ fields: ["user_name"] }
	).then(function (response) {
		// into the main index, updating the page

		// var dbusers = {
		// 	users: dbusers,
		// };
		return res.json(response);
	});
	// let's assume the default of isAdmin is false
	console.log(req); // 'alice123'
});`

**Comment by juanlajara** [comment]
I tried user_name: req.body.user_name instead of user_name: "TestIt" but can't seem to get postman to send the body

**Comment by antoniojgage** [comment]
What's the error exactly?
